version: 2
jobs:
  testing:
    docker:
       - image: alekzonder/puppeteer:latest
    steps:
        - checkout
        - run: export CSS_URL=https://cd1st.identitymind.com/idm.min.css
        - run: export DV_CHECK=https://pluginst.identitymind.com/api/dv
        - run: export INIT_API_URL=https://pluginst.identitymind.com/api/init
        - run: export LOADING_WHEEL=https://cd1st.identitymind.com/spinner.gif
        - run: export NEW_RELIC_URL=https://cd1st.identitymind.com/newrelic-stg.min.js
        - run: export PLUGIN_BASE_URL=https://cd1st.identitymind.com/
        - run: export ROUTER_API_URL=https://pluginst.identitymind.com/api/router
        - run: export SMS_API_URL=https://pluginst.identitymind.com/api/sms
        - run: export SOCKET_BASE_URL=https://kyc-plugin-socketio-staging.herokuapp.com/
        - run: export FILES_API_URL=https://pluginst.identitymind.com/api/files
        - run: export URL_WH_SENTRY=/wh/sentry_messange/
        - run: npm install
        - run: npm run test
        - store_artifacts:
            path: tests.xml

  sandbox:

      docker:
       - image: alekzonder/puppeteer:latest
      steps:
        - checkout
        - run: echo "run staging"
      variables:
        CSS_URL: htpp.//google.com
        CSS_URL2: htpp.//google.com
        CSS_URL3: htpp.//google.com
  
  amldemo:
      docker:
       - image: alekzonder/puppeteer:latest
      steps:
        - checkout
        - run: echo "run aml demo"

  staging:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"

workflows:
  version: 2
  deploy_plugin_test:
    jobs:
      - testing
      - amldemo:
          filters:
            branches:
                ignore:
                    - master
          type: approval
          requires:
            - testing
      - sandbox:
          filters:
            branches:
                only:
                  - master
          type: approval
          requires:
            - testing
      - staging:
          requires:
            - sandbox
          filters:
            branches:
              only:
                - master
          
        
