version: 2
jobs:
   sanbox:
     type: approval
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
   staging:
     type: approval
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A more familiar hi".
       
    hold:
     type: approval
     requires:
      sandbox      
      staging
      
workflows:
   version: 2
   one_and_two:
     jobs:
       hold
   
   
