version: 2
jobs:
  testing:
    docker:
       - image: circleci/node:4.8.2
    steps:
        - checkout
        - run: echo "testing"

  sandbox:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"
  
  amldemo:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run aml demo"
workflows:
  jobs:
    - testing
    - sandbox
    - amldemo
          
