version: 2
jobs:
  testing:
    docker:
       - image: circleci/node:4.8.2
    steps:
        - checkout
        - run: echo "testing"

  sandbox:

      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"
  
  amldemo:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run aml demo"

  staging:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"

workflows:
  version: 2
  deploy_plugin_test:
    jobs:
      - testing
      - amldemo:
          type: approval
          requires:
            - testing
      - sandbox:
          type: approval
          requires:
            - amldemo
      - staging:
          filters:
            branches:
              only:
                - master
