version: 2
jobs:
  testing:
    docker:
       - image: circleci/node:4.8.2
    steps:
        - checkout
        - run: echo "testing"

  sandbox:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"
  
  amldemo:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run aml demo"

workflows:
  version: 2
  deploy_plugin_test:
    jobs:
      - testing
      - sandbox:
          type: approval
          requires:
            - testing
      - amldemo:
          type: approval
          branches:
            only:
              - master
          requires:
            - sandbox
