version: 2
jobs:
  testing:
    docker:
       - image: circleci/node:4.8.2
    steps:
        - checkout
        - run: echo "testing"

  sandbox:

      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"
      variables:
        CSS_URL: htpp.//google.com
        CSS_URL2: htpp.//google.com
        CSS_URL3: htpp.//google.com
  
  amldemo:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run aml demo"

  staging:
      docker:
       - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "run staging"

workflows:
  version: 2
  deploy_plugin_test:
    jobs:
      - testing
      - amldemo:
          type: approval
          requires:
            - testing
      - sandbox:
          type: approval
          requires:
            - amldemo
      - staging:
          requires:
            - sandbox
          filters:
            branches:
              only:
                - master
          
        
      
      
